# Generated by Django 3.2 on 2021-04-22 12:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210422_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='isbn',
            name='isbn_number',
            field=models.IntegerField(default=uuid.UUID('84903034-33d3-45b1-b30a-356da70974ca'), null=True),
        ),
    ]
