# Generated by Django 3.2 on 2021-04-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210422_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isbn',
            name='isbn_number',
            field=models.IntegerField(default='7951798425', null=True, unique=True),
        ),
    ]
