# Generated by Django 3.2 on 2021-04-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_isbn_isbn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isbn',
            name='isbn_number',
            field=models.IntegerField(default='4258767577', null=True, unique=True),
        ),
    ]
