# Generated by Django 3.2 on 2021-04-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20210422_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isbn',
            name='isbn_number',
            field=models.IntegerField(default='53477146', null=True, unique=True),
        ),
    ]
